# Generated by Django 5.1 on 2025-04-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
            },
        ),
        migrations.CreateModel(
            name='RecursoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('LIB', 'Libro'), ('REV', 'Revista'), ('ART', 'Artículo'), ('TES', 'Tesis'), ('AUD', 'Audio'), ('VID', 'Video'), ('SOF', 'Software'), ('OTR', 'Otro')], max_length=3)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('editorial', models.CharField(max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('doi', models.CharField(blank=True, max_length=50, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('archivo_digital', models.FileField(blank=True, null=True, upload_to='recursos/')),
                ('url_externa', models.URLField(blank=True, null=True)),
                ('palabras_clave', models.CharField(blank=True, max_length=200)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recurso Digital',
                'verbose_name_plural': 'Recursos Digitales',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
