# Generated by Django 5.1 on 2025-04-22 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='responsable',
            field=models.ForeignKey(limit_choices_to={'tipo__in': ['BIB', 'ADM']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='recursos',
            field=models.ManyToManyField(related_name='colecciones', to='catalogo.recursodigital'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='recursos',
            field=models.ManyToManyField(related_name='categorias', to='catalogo.recursodigital'),
        ),
    ]
