# Generated by Django 5.1 on 2025-04-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('pagada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('SOL', 'Solicitado'), ('APR', 'Aprobado'), ('REC', 'Rechazado'), ('CUR', 'En curso'), ('DEV', 'Devuelto'), ('VEN', 'Vencido'), ('CAN', 'Cancelado')], default='SOL', max_length=3)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_reserva', models.DateTimeField()),
                ('estado', models.CharField(choices=[('SOL', 'Solicitado'), ('APR', 'Aprobado'), ('REC', 'Rechazado'), ('CUR', 'En curso'), ('DEV', 'Devuelto'), ('VEN', 'Vencido'), ('CAN', 'Cancelado')], default='SOL', max_length=3)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
