# Generated by Django 5.1 on 2025-04-22 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('DIS', 'Disponible'), ('PRE', 'Prestado'), ('RES', 'Reservado'), ('REP', 'En reparación'), ('PER', 'Perdido'), ('RET', 'Retirado')], default='DIS', max_length=3)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_adquisicion', models.DateField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.recursodigital')),
            ],
            options={
                'verbose_name': 'Ejemplar',
                'verbose_name_plural': 'Ejemplares',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('DIS', 'Disponible'), ('PRE', 'Prestado'), ('RES', 'Reservado'), ('REP', 'En reparación'), ('PER', 'Perdido'), ('RET', 'Retirado')], max_length=3)),
                ('estado_nuevo', models.CharField(choices=[('DIS', 'Disponible'), ('PRE', 'Prestado'), ('RES', 'Reservado'), ('REP', 'En reparación'), ('PER', 'Perdido'), ('RET', 'Retirado')], max_length=3)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='ejemplares.ejemplar')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
